version: '3'

services:

  node:
    image: node
    working_dir: /app
    command: npm start
    volumes:
      - ./:/app
    environment:
      - ETHEREUM_NET
      - SENDER_PRIVATE_KEY
      - CONTRACT_ADDRESS
